SELECT NAME, COUNTRY, NUMGUNS, LAUNCHED
FROM SHIPS JOIN CLASSES ON SHIPS.CLASS=CLASSES.CLASS;

SELECT NAME, COUNTRY, NUMGUNS, LAUNCHED
FROM CLASSES LEFT JOIN SHIPS ON SHIPS.CLASS=CLASSES.CLASS;

SELECT SHIPS.NAME
FROM SHIPS JOIN OUTCOMES ON SHIPS.NAME=OUTCOMES.SHIP JOIN BATTLES ON OUTCOMES.BATTLE=BATTLES.NAME
WHERE DATE LIKE '1942%';

SELECT NAME
FROM SHIPS AS S1
WHERE NOT EXISTS (SELECT * FROM SHIPS AS S2 JOIN OUTCOMES ON S2.NAME=OUTCOMES.SHIP WHERE S2.NAME=S1.NAME);